version: '3.8'

services:
  rustdesk-console:
    image: databk/rustdesk-console:latest
    container_name: rustdesk-console
    restart: unless-stopped
    networks:
      - rustdesk-network

  rustdesk-console-web:
    image: databk/rustdesk-console-web:latest
    container_name: rustdesk-console-web
    ports:
      - "21114:80"
    depends_on:
      - rustdesk-console
    restart: unless-stopped
    networks:
      - rustdesk-network

networks:
  rustdesk-network:
    driver: bridge
