import type { ConfigOption } from '../types';

export const options: ConfigOption[] = [
  {
    key: 'enable-lan-discovery',
    label: 'enable-lan-discovery',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'direct-server',
    label: 'direct-server',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-auto-update',
    label: 'allow-auto-update',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-abr',
    label: 'enable-abr',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-linux-headless',
    label: 'allow-linux-headless',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'sync-ab-with-recent-sessions',
    label: 'sync-ab-with-recent-sessions',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'sync-ab-tags',
    label: 'sync-ab-tags',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'filter-ab-by-intersection',
    label: 'filter-ab-by-intersection',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-udp-punch',
    label: 'enable-udp-punch',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-ipv6-punch',
    label: 'enable-ipv6-punch',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
    description: 'Self-hosted: N, others: Y',
  },
  {
    key: 'pre-elevate-service',
    label: 'pre-elevate-service',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'keep-awake-during-incoming-sessions',
    label: 'keep-awake-during-incoming-sessions',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'keep-awake-during-outgoing-sessions',
    label: 'keep-awake-during-outgoing-sessions',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-udp',
    label: 'disable-udp',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-https-21114',
    label: 'allow-https-21114',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-hostname-as-id',
    label: 'allow-hostname-as-id',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-websocket',
    label: 'allow-websocket',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'register-device',
    label: 'register-device',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-command-line-settings-when-settings-disabled',
    label: 'allow-command-line-settings-when-settings-disabled',
    category: 'advanced',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
];
