import type { ConfigOption } from '../types';

export const options: ConfigOption[] = [
  {
    key: 'enable-audio',
    label: 'enable-audio',
    category: 'av',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-always-software-render',
    label: 'allow-always-software-render',
    category: 'av',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-hwcodec',
    label: 'enable-hwcodec',
    category: 'av',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'use-texture-render',
    label: 'use-texture-render',
    category: 'av',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
    description: 'Platform dependent',
  },
  {
    key: 'disable-audio',
    label: 'disable-audio',
    category: 'av',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'i444',
    label: 'i444',
    category: 'av',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'image-quality',
    label: 'image-quality',
    category: 'av',
    type: 'select',
    defaultValue: 'balanced',
    options: ['best', 'balanced', 'low', 'custom'],
  },
  {
    key: 'custom-image-quality',
    label: 'custom-image-quality',
    category: 'av',
    type: 'number',
    defaultValue: '50',
    min: 10,
    max: 2000,
  },
  {
    key: 'custom-fps',
    label: 'custom-fps',
    category: 'av',
    type: 'number',
    defaultValue: '30',
    min: 5,
    max: 120,
  },
  {
    key: 'enable-directx-capture',
    label: 'enable-directx-capture',
    category: 'av',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-android-software-encoding-half-scale',
    label: 'enable-android-software-encoding-half-scale',
    category: 'av',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-d3d-render',
    label: 'allow-d3d-render',
    category: 'av',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
];
