import type { ConfigOption } from '../types';

export const options: ConfigOption[] = [
  {
    key: 'access-mode',
    label: 'access-mode',
    category: 'connection',
    type: 'select',
    defaultValue: 'custom',
    options: ['custom', 'full', 'view'],
  },
  {
    key: 'enable-keyboard',
    label: 'enable-keyboard',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-clipboard',
    label: 'enable-clipboard',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-file-transfer',
    label: 'enable-file-transfer',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-camera',
    label: 'enable-camera',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-terminal',
    label: 'enable-terminal',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-remote-printer',
    label: 'enable-remote-printer',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-tunnel',
    label: 'enable-tunnel',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-remote-restart',
    label: 'enable-remote-restart',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-block-input',
    label: 'enable-block-input',
    category: 'connection',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-auto-disconnect',
    label: 'allow-auto-disconnect',
    category: 'connection',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'auto-disconnect-timeout',
    label: 'auto-disconnect-timeout',
    category: 'connection',
    type: 'number',
    defaultValue: '10',
    min: 1,
    max: 9999,
    description: 'Timeout in minutes',
  },
  {
    key: 'allow-only-conn-window-open',
    label: 'allow-only-conn-window-open',
    category: 'connection',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'view-only',
    label: 'view-only',
    category: 'connection',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'terminal-persistent',
    label: 'terminal-persistent',
    category: 'connection',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-ask-for-note',
    label: 'allow-ask-for-note',
    category: 'connection',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
];
