import type { ConfigOption } from '../types';

export const options: ConfigOption[] = [
  {
    key: 'theme',
    label: 'theme',
    category: 'display',
    type: 'select',
    defaultValue: 'system',
    options: ['dark', 'light', 'system'],
  },
  {
    key: 'lang',
    label: 'lang',
    category: 'display',
    type: 'text',
    defaultValue: 'default',
    description: 'Language code',
  },
  {
    key: 'enable-confirm-closing-tabs',
    label: 'enable-confirm-closing-tabs',
    category: 'display',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-remove-wallpaper',
    label: 'allow-remove-wallpaper',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-open-new-connections-in-tabs',
    label: 'enable-open-new-connections-in-tabs',
    category: 'display',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'peer-card-ui-type',
    label: 'peer-card-ui-type',
    category: 'display',
    type: 'select',
    defaultValue: '0',
    options: ['0', '1', '2'],
  },
  {
    key: 'peer-sorting',
    label: 'peer-sorting',
    category: 'display',
    type: 'select',
    defaultValue: 'Remote ID',
    options: ['Remote ID', 'Remote Host', 'Username'],
  },
  {
    key: 'show-monitors-toolbar',
    label: 'show-monitors-toolbar',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'collapse-toolbar',
    label: 'collapse-toolbar',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'show-remote-cursor',
    label: 'show-remote-cursor',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'follow-remote-cursor',
    label: 'follow-remote-cursor',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'follow-remote-window',
    label: 'follow-remote-window',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'zoom-cursor',
    label: 'zoom-cursor',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'show-quality-monitor',
    label: 'show-quality-monitor',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'reverse-mouse-wheel',
    label: 'reverse-mouse-wheel',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'swap-left-right-mouse',
    label: 'swap-left-right-mouse',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'displays-as-individual-windows',
    label: 'displays-as-individual-windows',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'use-all-my-displays-for-the-remote-session',
    label: 'use-all-my-displays-for-the-remote-session',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'view-style',
    label: 'view-style',
    category: 'display',
    type: 'select',
    defaultValue: 'original',
    options: ['original', 'adaptive'],
  },
  {
    key: 'scroll-style',
    label: 'scroll-style',
    category: 'display',
    type: 'select',
    defaultValue: 'scrollauto',
    options: ['scrollauto', 'scrollbar', 'scrolledge'],
  },
  {
    key: 'edge-scroll-edge-thickness',
    label: 'edge-scroll-edge-thickness',
    category: 'display',
    type: 'number',
    defaultValue: '100',
    min: 20,
    max: 150,
  },
  {
    key: 'trackpad-speed',
    label: 'trackpad-speed',
    category: 'display',
    type: 'number',
    defaultValue: '100',
    min: 10,
    max: 1000,
  },
  {
    key: 'disable-group-panel',
    label: 'disable-group-panel',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'keep-screen-on',
    label: 'keep-screen-on',
    category: 'display',
    type: 'select',
    defaultValue: 'during-controlled',
    options: ['never', 'during-controlled', 'service-on'],
  },
  {
    key: 'main-window-always-on-top',
    label: 'main-window-always-on-top',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-discovery-panel',
    label: 'disable-discovery-panel',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'touch-mode',
    label: 'touch-mode',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'show-virtual-mouse',
    label: 'show-virtual-mouse',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'show-virtual-joystick',
    label: 'show-virtual-joystick',
    category: 'display',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
];
