import type { ConfigOption } from '../types';

export const options: ConfigOption[] = [
  {
    key: 'hide-security-settings',
    label: 'hide-security-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-network-settings',
    label: 'hide-network-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-server-settings',
    label: 'hide-server-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-proxy-settings',
    label: 'hide-proxy-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-websocket-settings',
    label: 'hide-websocket-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-remote-printer-settings',
    label: 'hide-remote-printer-settings',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-username-on-card',
    label: 'hide-username-on-card',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-help-cards',
    label: 'hide-help-cards',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-tray',
    label: 'hide-tray',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'hide-stop-service',
    label: 'hide-stop-service',
    category: 'hide',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
];
