import type { ConfigOption } from '../types';

export const options: ConfigOption[] = [
  {
    key: 'allow-remote-config-modification',
    label: 'allow-remote-config-modification',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'whitelist',
    label: 'whitelist',
    category: 'security',
    type: 'text',
    defaultValue: '',
    description: 'Comma-separated IP list',
  },
  {
    key: 'approve-mode',
    label: 'approve-mode',
    category: 'security',
    type: 'select',
    defaultValue: 'password-click',
    options: ['password', 'click', 'password-click'],
  },
  {
    key: 'verification-method',
    label: 'verification-method',
    category: 'security',
    type: 'select',
    defaultValue: 'use-both-passwords',
    options: [
      'use-temporary-password',
      'use-permanent-password',
      'use-both-passwords',
    ],
  },
  {
    key: 'temporary-password-length',
    label: 'temporary-password-length',
    category: 'security',
    type: 'select',
    defaultValue: '6',
    options: ['6', '8', '10'],
  },
  {
    key: 'lock-after-session-end',
    label: 'lock-after-session-end',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-remote-cm-modification',
    label: 'allow-remote-cm-modification',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'remove-preset-password-warning',
    label: 'remove-preset-password-warning',
    category: 'security',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'enable-trusted-devices',
    label: 'enable-trusted-devices',
    category: 'security',
    type: 'switch',
    defaultValue: 'Y',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-logon-screen-password',
    label: 'allow-logon-screen-password',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-numeric-one-time-password',
    label: 'allow-numeric-one-time-password',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'allow-insecure-tls-fallback',
    label: 'allow-insecure-tls-fallback',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-change-permanent-password',
    label: 'disable-change-permanent-password',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-change-id',
    label: 'disable-change-id',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
  {
    key: 'disable-unlock-pin',
    label: 'disable-unlock-pin',
    category: 'security',
    type: 'switch',
    defaultValue: 'N',
    options: ['Y', 'N'],
  },
];
